services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_home
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql
      
    networks:
      - shm_network
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
    container_name: flask_app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    networks:
      - shm_network
    depends_on:
      - db  # Ensure the db service starts before the app
    volumes:
      - ./app:/app  # Mount the Flask app's directory for live reloading


  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shm_network
    depends_on:
      - app

networks:
  shm_network:
    driver: bridge

volumes:
  mysql_data:
 
